# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_web_webtoscrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='webToScrap',
        ),
    ]
